sudoers: ["admins"] #grps with admin privilage, should be added in groups

channel_url: "t.me/theostrich"
group_url  : "t.me/ostrichdiscussion"
donation_url: "https://paypal.me/donateostrich"

force_sub: true

domains: ['mail.bruva.co']

groups:
- name: "free"
  limits: 
    max_mails: 3   
- name: "premium"
  limits: 
    max_mails: 5
- name: "admins"
  users: [1775541139, 1520625615, 1809735866]
  limits: 
    max_mails: 5


broadcast:
users: all    #no. of users to send the message to
mode: forward #available options: forward, copy

reserved_keyword : [
    'admin', 'owner', 'contact', 'support', 'donate', 'postmaster', 'message',
    'ostrich', 'administrator', 'access', 'account', 'mail', 'email', 'patner',
    'admins', 'porn', 'gov', 'government', 'noreply', 'subscribe', 'free',
    'paid', 'api', 'auth', 'dev', 'developers', 'docs', 'faq', 'group',
    'groups', 'help', 'hostmaster', 'join', 'local', 'login', 'master',
    'register', 'root', 'terms', 'user', 'webmaster', 'quantum', 'theostrich',
    'chat', 'melvik', 'storm', 'melvikstorm'
]

MongoDB:
  database: mailable
  collection: usercache
